import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { authUserSession } from "@/libs/auth-libs";
import Providers from "./providers";
import LayoutWrapper from "@/components/Layout-Client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NeoVoid",
  description: "Generated by ShadowOverload",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await authUserSession();


  // return (
  //   <html lang="en">
  //     <body
  //       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
  //     >
  //       <Providers>
  //         <Navbar session={session} />
  //         {children}
  //         <Footer />
  //       </Providers>
  //     </body>
  //   </html>
  // );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <LayoutWrapper session={session}>
            {children}
          </LayoutWrapper>
        </Providers>
      </body>
    </html>
  );
}
